title: "史蒂芬软件站"
description: "软件改变世界"

url: http://www.sdfen.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: "Home"
   url: /index.html
 - title: Mac
   url: /mac
 - title: Window
   url: /window

social:
   github: sdfen
   twitter: sdfen
   facebook: sdfen
   email: sdfen@gmail.com

google_analytics: "UA-58263416-1"
